#!/usr/bin/env node
/**
 * Daily Digest Generator
 * 
 * Fetches tech news from multiple sources, filters top 10,
 * generates text + HTML outputs.
 */

const { writeFileSync, mkdirSync, existsSync } = require('fs');
const { join } = require('path');

// Configuration
const OUTPUT_BASE = join(process.env.HOME || '~', '.openclaw/workspace/contents/daily-digest');
const TODAY = new Date().toISOString().split('T')[0];

// Priority 1: Headline companies
const HEADLINE_COMPANIES = [
  'OpenAI', 'Anthropic', 'Google', 'Gemini', 'Meta', 'xAI', 'Microsoft',
  '阿里巴巴', '腾讯', 'DeepSeek', 'Kimi', '智谱', 'GLM'
];

// Priority 2: AI Coding topics
const AI_CODING_KEYWORDS = [
  'Claude Code', 'Codex', 'Cursor', 'Windsurf', 'Copilot',
  'AI coding', 'AI agent', 'MCP protocol'
];

// Priority 3: Trusted sources
const TRUSTED_SOURCES = [
  "Lenny's Podcast", 'Y Combinator', 'The Pragmatic Engineer', 'a16z',
  'Simon Willison', '宝玉', '张小珺', '腾讯科技', '极客公园'
];

/**
 * Filter and rank news items
 */
function filterAndRank(items) {
  const scored = items.map((item, idx) => {
    let priority = 4; // Default: content quality
    let reason = '内容质量高';

    // Priority 1: Headline companies
    if (HEADLINE_COMPANIES.some(c => item.title.includes(c) || (item.source && item.source.includes(c)))) {
      priority = 1;
      reason = '头部厂商重大动态';
    }
    // Priority 2: AI Coding
    else if (AI_CODING_KEYWORDS.some(k => item.title.toLowerCase().includes(k.toLowerCase()))) {
      priority = 2;
      reason = 'AI Coding 专题';
    }
    // Priority 3: Trusted sources
    else if (TRUSTED_SOURCES.some(s => (item.source && item.source.includes(s)))) {
      priority = 3;
      reason = '高优来源';
    }

    return {
      rank: 0,
      title: item.title,
      summary: item.summary || '',
      source: item.source || 'Unknown',
      url: item.url,
      score: item.score,
      reason,
      category: item.category || '综合',
      priority
    };
  });

  // Sort by priority, then by score
  scored.sort((a, b) => {
    if (a.priority !== b.priority) return a.priority - b.priority;
    return (b.score || 0) - (a.score || 0);
  });

  // Take top 10 and assign ranks
  return scored.slice(0, 10).map((item, idx) => ({
    ...item,
    rank: idx + 1,
    priority: undefined
  }));
}

/**
 * Extract keywords from digest
 */
function extractKeywords(digest) {
  const allText = digest.map(d => d.title + ' ' + d.summary).join(' ');
  const keywords = [];
  
  const candidates = ['AI', 'Claude', 'DeepSeek', 'Coding', 'LLM', 'Agent', 'OpenAI', '模型'];
  candidates.forEach(k => {
    if (allText.includes(k)) keywords.push(k);
  });

  return keywords.slice(0, 5);
}

/**
 * Generate plain text version
 */
function generateText(digest, date) {
  const lines = [];
  
  lines.push(`📰 技术早报 | ${date}`);
  lines.push('');

  // Headline (Top 1)
  const top1 = digest[0];
  lines.push('🔥 头条');
  lines.push(`[${top1.rank}] ${top1.title}`);
  lines.push(top1.summary);
  lines.push(`来源：${top1.source} | HN 评分：${top1.score || 'N/A'}`);
  lines.push(top1.url);
  lines.push('');

  // AI Dynamics
  lines.push('⚡ AI 动态');
  digest.slice(1, 5).forEach(item => {
    lines.push(`[${item.rank}] ${item.title}`);
    lines.push(item.summary || '一句话摘要...');
    lines.push(`来源：${item.source} | HN 评分：${item.score || 'N/A'}`);
    lines.push(item.url);
    lines.push('');
  });

  // Deep Reading
  lines.push('💡 深度阅读');
  digest.slice(5, 10).forEach(item => {
    lines.push(`• ${item.title} - ${item.url}`);
  });
  lines.push('');

  // Keywords
  const keywords = extractKeywords(digest);
  lines.push(`🏷️ 关键词：${keywords.join(' / ')}`);
  lines.push('');
  lines.push('---');
  lines.push('Generated by Daily Digest');

  return lines.join('\n');
}

/**
 * Generate magazine-style HTML
 */
function generateHTML(digest, date) {
  const top1 = digest[0];
  const others = digest.slice(1);
  const keywords = extractKeywords(digest);

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>技术早报 | ${date}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #fefdfb;
      font-family: -apple-system, 'PingFang SC', 'Helvetica Neue', sans-serif;
      color: #374151;
      line-height: 1.6;
      padding: 40px 20px;
    }
    .container { max-width: 640px; margin: 0 auto; }
    h1 {
      font-family: Georgia, 'Noto Serif SC', serif;
      color: #1a365d;
      font-size: 24px;
      letter-spacing: 0.05em;
      margin-bottom: 8px;
    }
    .date { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
    .keywords { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 32px; }
    .keyword {
      border: 1px solid #1a365d;
      color: #1a365d;
      padding: 4px 12px;
      border-radius: 16px;
      font-size: 12px;
    }
    .card {
      margin-bottom: 32px;
      padding: 24px;
      border-left: 3px solid #d97706;
      background: rgba(217, 119, 6, 0.06);
    }
    .card.regular {
      border-left: none;
      background: none;
      padding: 16px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .rank {
      font-family: 'Inter', sans-serif;
      color: #1a365d;
      font-weight: bold;
      margin-right: 8px;
    }
    .title {
      font-family: Georgia, 'Noto Serif SC', serif;
      color: #1a365d;
      font-size: 17px;
      text-decoration: none;
    }
    .title:hover { text-decoration: underline; }
    .summary { margin-top: 12px; font-size: 14px; color: #374151; }
    .meta { margin-top: 12px; font-size: 12px; color: #6b7280; }
    .footer {
      margin-top: 48px;
      padding-top: 24px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
    }
    .footer-brand {
      font-family: Georgia, 'Noto Serif SC', serif;
      color: #1a365d;
      letter-spacing: 0.05em;
      margin-bottom: 4px;
    }
    .footer-tagline { font-size: 12px; color: #6b7280; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Daily Digest</h1>
    <div class="date">${date}</div>
    <div class="keywords">
      ${keywords.map(k => `<span class="keyword">${k}</span>`).join('')}
    </div>
    <div class="card">
      <span class="rank">#1</span>
      <a href="${top1.url}" class="title" target="_blank">${top1.title}</a>
      <div class="summary">${top1.summary}</div>
      <div class="meta">来源：${top1.source} | 评分：${top1.score || 'N/A'} | ${top1.reason}</div>
    </div>
    ${others.map(item => `
      <div class="card regular">
        <span class="rank">#${item.rank}</span>
        <a href="${item.url}" class="title" target="_blank">${item.title}</a>
        <div class="summary">${item.summary || ''}</div>
        <div class="meta">来源：${item.source} | 评分：${item.score || 'N/A'}</div>
      </div>
    `).join('')}
    <div class="footer">
      <div class="footer-brand">Daily Digest</div>
      <div class="footer-tagline">遇见更好的技术阅读</div>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Main execution
 */
async function main() {
  const outputDir = join(OUTPUT_BASE, TODAY);
  
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Sample data (will be replaced with actual fetched data)
  const sampleItems = [
    {
      title: 'Claude Code 新功能：支持多文件编辑',
      summary: 'Anthropic 发布 Claude Code 更新，支持同时编辑多个文件，大幅提升编码效率',
      source: 'Anthropic Blog',
      url: 'https://anthropic.com/news/claude-code-update',
      score: 350,
      category: 'AI Coding'
    },
    {
      title: 'DeepSeek V3 技术报告详解',
      summary: '深度解析 DeepSeek V3 的架构设计和训练方法',
      source: '知乎',
      url: 'https://zhihu.com/question/deepseek-v3',
      score: 280,
      category: 'AI'
    },
    {
      title: 'OpenAI 发布 GPT-5 预告片',
      summary: 'Sam Altman 在 X 上发布 GPT-5 预告片，暗示下周正式发布',
      source: 'X / Twitter',
      url: 'https://twitter.com/sama/status/xxx',
      score: 520,
      category: 'AI'
    },
    {
      title: 'Cursor 新版本支持本地模型',
      summary: 'Cursor 1.5 发布，支持运行本地 LLM，隐私友好',
      source: 'Cursor Blog',
      url: 'https://cursor.sh/blog/1.5',
      score: 290,
      category: 'AI Coding'
    },
    {
      title: 'AI 编程工具对比：Claude Code vs Cursor vs Copilot',
      summary: '深度对比三款主流 AI 编程工具的优缺点',
      source: 'The Pragmatic Engineer',
      url: 'https://blog.pragmaticengineer.com/ai-coding-tools',
      score: 410,
      category: 'AI Coding'
    }
  ];

  const digest = filterAndRank(sampleItems);
  
  // Generate outputs
  const textOutput = generateText(digest, TODAY);
  const htmlOutput = generateHTML(digest, TODAY);

  // Save files
  writeFileSync(join(outputDir, 'digest.txt'), textOutput);
  writeFileSync(join(outputDir, 'digest.html'), htmlOutput);

  console.log(`✅ Daily Digest generated: ${outputDir}`);
  console.log('\n📄 Text output:');
  console.log(textOutput);
  console.log('\n📁 Files saved:');
  console.log(`   - ${join(outputDir, 'digest.txt')}`);
  console.log(`   - ${join(outputDir, 'digest.html')}`);
}

main().catch(console.error);
